import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import { useEffect, useState } from 'react'
import useSWR from 'swr';
import Chessboard from '@/components/chessboard';


const inter = Inter({ subsets: ['latin'] })

//const fetcher = (url: string) => fetch(url, 
//  {"body": JSON.stringify({"opening": "London System"}), "method": "GET"}
//).then((res) => res.json())
const fetcher = (url: string) => fetch(url).then((res) => res.json())

const Home = () => {
  const [lastMoveIsCorrect, setLastMoveIsCorrect] = useState<boolean | null>(null);
  const [openingName, setOpeningName] = useState<string>('London System')
  const { data, error, isLoading } = useSWR(
    `/api/openings/?opening=${openingName}`, 
    fetcher
    //(url) => fetch(
    //  url, 
    //  {
    //    body: JSON.stringify({"opening": openingName})
    //  }
    //).then((res) => res.json())
  );
  const [pgn, setPgn] = useState<string>('');

  useEffect(() => {
    if (data?.pgn) {
      setPgn(data.pgn)
    }
  }, [data])

  useEffect(() => {
    console.log(pgn);
  }, [pgn])

  return (
    <>
      <Head>
        <title>Chess Opening Trainer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* // center the chessboard with flexbox */}
      <div className="flex w-screen h-screen justify-center items-center flex-col">
        <input type="text" value={openingName} onChange={(e) => setOpeningName(e.target.value)} />
        {lastMoveIsCorrect === null ? null : lastMoveIsCorrect ? <p>Correct!</p> : <p>Incorrect!</p>}
        <div className=" grow aspect-square">
          <Chessboard onMove={(currentPgn: any) => {
            console.log(pgn);
            console.log(currentPgn);
            if (pgn.includes(currentPgn)) {
              console.log('correct move')
              setLastMoveIsCorrect(true);
            } else {
              console.log('incorrect move')
              setLastMoveIsCorrect(false);
            }
          }}/>
        </div>
      </div>
    </>
  )
}

export default Home;